#!/bin/bash

disk=/Volumes/No\ Name
folder="$disk"/DCIM/100GOPRO
arkive=~/Desktop/$(date +%Y%m%d)

#Creates a new arkive folder
mkdir -p "$arkive"

#Deletes .LRV and .THM files from source
rm "$folder"/*.LRV
rm "$folder"/*.THM

# Creates a hidden file with all of the filenames in folder
ls -1 "$folder" >> "$arkive"/.filenames

#Moves all files from the source to the arkive, but does not overwrite existing files
# and appends T_ to the front of all the filenames
while read filename; do
  mv -n "$folder"/$filename "$arkive"/T_$filename;
done <"$arkive"/.filenames

#deletes .filenames
rm "$arkive"/.filenames

#umounts the source disk
#diskutil unmount "$disk"

# # Finds the newest file in the arkive
# unset -v latest
# for file in "$arkive"/*; do
#   [[ $file -nt $latest ]] && latest=$file
# done

# #Opens the arkive folder
open "$arkive"

# # Opens the newest video in the arkive folder
# open "$file"

# Opens all of the videos in the arkive folder
# open "$arkive"/*.MP4

# #Opens the newest file in the arkive folder flipped up side down and in full screen usin VLC
#/Applications/VLC.app/Contents/MacOS/VLC "$file" --video-filter=transform --transform-type=180 --fullscreen
