#!/bin/bash	

disk=/Volumes/No\ Name/
kilde="$disk"AFF\ reklame
arkiv=~/Desktop/$(date +%Y%m%d)

#Lager ny arkivmappe dersom den ikke eksisterer
mkdir -p "$arkiv"

#kopierer alle filer fra kilde til akriv, men overskriver ikke
mv -n "$kilde"/* "$arkiv"

#Kobler fra volumet
diskutil unmount "$disk"

# Finner nyeste fil i arkivet
unset -v latest
for file in "$arkiv"/*; do
  [[ $file -nt $latest ]] && latest=$file
done

#Åpner mappen til nyeste fil i arkivet og åpner samme fil i Quicktime
open -R "$file"
open "$file"

#Åpner video flippet og fullscreen i VLC
#/Applications/VLC.app/Contents/MacOS/VLC "$file" --video-filter=transform --transform-type=180 --fullscreen
