#!/bin/bash	

# Brukerhistorie
# lag mappe for tandem video og bilder
# kopier videoredigerings template
# flytt alle bilder til bilde arkiv
# flytt alle videoer til redigerings bibliotek
# flytt alle bilder til usb pinne

#disk=/Volumes/No\ Name/
#kilde="$disk"AFF\ reklame
bildearkiv=~/Desktop/$(date +%Y%m%d)/bilder

#Lager ny arkivmappe dersom den ikke eksisterer
mkdir -p "$bildearkiv"

#kopierer nyeste fil fra kilde til akriv, men overskriver ikke
#mv -n "$kilde"/* "$arkiv"

#Kobler fra volumet
#diskutil unmount "$disk"