#!/bin/bash	

kilde=/Volumes/NO\ NAME/AFF\ reklame
arkiv=~/Desktop/$(date +%Y%m%d)

#Lager ny arkivmappe dersom den ikke eksisterer
mkdir -p "$arkiv"

# Finner nyeste fil i kilden
unset -v latest
for file in "$kilde"/*; do
  [[ $file -nt $latest ]] && latest=$file
done

#kopierer nyeste fil fra kilde til akriv, men overskriver ikke
cp -n "$file" "$arkiv"

#Kobler fra volumet
diskutil unmount /Volumes/NO\ NAME

# Finner nyeste fil i arkivet
unset -v latest
for file in "$arkiv"/*; do
  [[ $file -nt $latest ]] && latest=$file
done

#Åpner mappen til nyeste fil i arkivet og opner samme fil i VLC
open -R "$file"
#open -a /Applications/VLC.app "$file"

#Åpner video flippet og fullscreen i VLC
/Applications/VLC.app/Contents/MacOS/VLC "$file" --video-filter=transform --transform-type=180 --fullscreen
